### ISSUE TITLE
Refactor GUI : page TestCase.jsp

### ISSUE THREAD

**Issue by afnogueira** [cerberustesting/cerberus-source#575]
This issue sums up the set of requirements and issues that should be considered while refactoring the page TestCase.jsp.

**Steps:**
- [x] UseStep can be set as Library Step #572
- [x] Test case update of UseStep information saves test case immediately #570
- [x] Test case update with Step library can create a mess on test cases that use UseStep #569
- [x] The useStep feature lists steps and test cases that are not marked as "in Library". #589
- [x] [TestCase] Editable components in step that uses another step bug #592
- [x] Edit Testcase Page : Have by default an empty step with an empty action #476 
- [ ] [EDIT TESTCASE] Use all step of a testcase #411 
- [x] When you save a step with the same number as another step, it gets overwritten #611

**Actions and Controls:**
- [x] not saving actions with \" character combination #552 
- [ ] Change the actions done for the instruction : "Select" #558
- [x] ENGINE] Add a specific control : verify ignore case #474
- [x] Idea : Add an action type "manual action" #456
- [x] In a verifyRegex, precisely identify differences between 2 elements #273

**Properties:**
- [x] Make a clickable link over a SOAP library ID #503
- [x] Countries checked by default when property is created #576
- [x] Create not defined property - select type of property #577
- [ ] Improve display of properties when use getfromDataLib : Display all data requested in the SQL Request #605

**Test case:**
- [ ] Rename a test #289 
- [ ] Export testcase / import testcase (JSON format) #260
- [x] Test case is not completely saved if user presses the Save button while the page is loading #581
- [x] Test case without number not editable #616

**Refactor: Code and GUI:**
- [x] Refactor of GUI #334
- [ ] Make the GUI and documentation multilanguage #566
- [x] Remove database access from Web pages (JSP) #389

**Comment by pfoucray** [comment]
Ideas I have on version **Cerberus1.1.10-SNAPSHOT-990**

- [ ] Inherited properties : add a link to go to Original library Test Case next to **each** property as inherited properties can come from different libraries. Same link as the one on top of use-steps. It could be a button into properties details
![image](https://cloud.githubusercontent.com/assets/16115517/20930680/a998357a-bbce-11e6-9a26-6b88afa3d602.png)

- [ ] Still Beeing able to free a use-step from it's library
![image](https://cloud.githubusercontent.com/assets/16115517/20930789/10e346c0-bbcf-11e6-9ef2-6be10298c207.png)

- [ ] Prevent to un-library a step if it has use-steps attached

- [ ] Still Beeing able to see use-steps attached to a Library

**Comment by vitoo** [comment]
Hi,

This button to add an action in first position of a step is missing in the new GUI : 
![image](https://cloud.githubusercontent.com/assets/995694/21725812/39150092-d43a-11e6-8d96-5c4c0cd64bce.png)

**Comment by vitoo** [comment]
Why we don't have the step number in this list ? can you put it back again ?

Thanks 

![image](https://cloud.githubusercontent.com/assets/995694/21978774/52f3b298-dbdc-11e6-936b-1e021b9c21d7.png)

**Comment by bcivel** [comment]
Hi @vitoo 
I put it there,
<img width="711" alt="capture d ecran 2017-01-16 a 11 24 38" src="https://cloud.githubusercontent.com/assets/5376184/21979265/79412190-dbde-11e6-934b-f4912ba67bcd.png">

Is it not enough?
Thanks
Benoit

**Comment by vitoo** [comment]
It require one more click to know the step number, less easy IMHO

**Comment by bcivel** [comment]
I close that huge issue as most of the job has been done.
Missing points will be followed on specified issue opened
